import { PrismaClient, InstitutionType, CampusSetting, TestPolicy, AcademicCalendar } from '@prisma/client'
import { SeedFunction } from './seedRunner'

export const universitiesSeed: SeedFunction = {
  name: 'universities',
  seed: async (prisma: PrismaClient) => {
    const universities = [
      {
        name: "Massachusetts Institute of Technology",
        slug: "mit",
        shortName: "MIT",
        description: "A world-class research university in Cambridge, Massachusetts, known for engineering and physical sciences. MIT is renowned for its rigorous academics, cutting-edge research, and innovative culture.",
        city: "Cambridge",
        state: "MA",
        zipCode: "02139",
        country: "USA",
        address: "77 Massachusetts Ave",
        latitude: 42.3601,
        longitude: -71.0942,
        logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/MIT_logo.svg/1024px-MIT_logo.svg.png",
        heroImageUrl: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=1200&h=600&fit=crop",
        websiteUrl: "https://www.mit.edu",
        established: 1861,
        
        climateZone: "Temperate",
        nearestAirport: "Boston Logan (BOS)",
        region: "Northeast",
        setting: CampusSetting.URBAN,
        campusSizeAcres: 168,
        
        type: InstitutionType.PRIVATE_NON_PROFIT,
        classification: "Research University",
        
        acceptanceRate: 0.04,
        applicationFee: 75,
        commonAppAccepted: true,
        applicationDeadline: new Date("2024-01-01"),
        earlyDecisionDeadline: new Date("2023-11-01"),
        testPolicy: TestPolicy.REQUIRED,
        minGpa: 3.8,
        avgGpa: 4.17,
        satMath25: 780,
        satMath75: 800,
        satVerbal25: 730,
        satVerbal75: 780,
        actComposite25: 35,
        actComposite75: 36,
        avgSatScore: 1545,
        avgActScore: 35,
        internationalEngReqs: { 
          toefl: { minimum: 100, recommended: 110 },
          ielts: { minimum: 7.5, recommended: 8.0 }
        },

        tuitionInState: 57986,
        tuitionOutState: 57986,
        tuitionInternational: 57986,
        roomAndBoard: 18790,
        booksAndSupplies: 1000,
        costOfLiving: 2000,
        percentReceivingAid: 0.58,
        averageGrantAid: 53000,
        averageNetPrice: 15000,
        needBlindAdmission: true,
        scholarshipsIntl: true,

        studentPopulation: 11934,
        undergraduatePopulation: 4638,
        graduatePopulation: 7296,
        studentFacultyRatio: 3,
        percentMale: 0.51,
        percentFemale: 0.49,
        percentInternational: 0.33,
        diversityScore: 0.85,

        graduationRate: 0.95,
        retentionRate: 0.98,
        employmentRate: 0.94,
        averageStartingSalary: 95000,
        internshipSupport: 5,
        alumniNetwork: 5,
        visaDurationMonths: 36,

        academicCalendar: AcademicCalendar.SEMESTER,
        sportsDivision: "NCAA Division III",
        hasHousing: true,
        studentLifeScore: 4.5,
        partySceneRating: 3.0,
        safetyRating: 4.8,
        
        popularMajors: ["Computer Science", "Mechanical Engineering", "Mathematics", "Physics", "Electrical Engineering"],
        degreeLevels: ["Bachelor's", "Master's", "PhD"],
        languages: ["English"],
        studentLifeTags: ["Research-focused", "Innovative", "Collaborative", "Tech-oriented"],
        rankings: { usNews: 1, forbes: 2, qs: 1 },
      },
      {
        name: "Stanford University",
        slug: "stanford",
        shortName: "Stanford",
        description: "Located in the heart of Silicon Valley, Stanford is known for its entrepreneurial spirit, academic excellence, and beautiful campus. It's a hub for innovation and startup culture.",
        city: "Stanford",
        state: "CA",
        zipCode: "94305",
        country: "USA",
        address: "450 Serra Mall",
        latitude: 37.4275,
        longitude: -122.1697,
        logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Seal_of_Leland_Stanford_Junior_University.svg/1024px-Seal_of_Leland_Stanford_Junior_University.svg.png",
        heroImageUrl: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=1200&h=600&fit=crop",
        websiteUrl: "https://www.stanford.edu",
        established: 1885,

        climateZone: "Mediterranean",
        nearestAirport: "San Jose (SJC) / SFO",
        region: "West Coast",
        setting: CampusSetting.SUBURBAN,
        campusSizeAcres: 8180,

        type: InstitutionType.PRIVATE_NON_PROFIT,
        classification: "Research University",

        acceptanceRate: 0.039,
        applicationFee: 90,
        commonAppAccepted: true,
        applicationDeadline: new Date("2024-01-05"),
        earlyDecisionDeadline: new Date("2023-11-01"),
        testPolicy: TestPolicy.OPTIONAL,
        minGpa: 3.85,
        avgGpa: 4.18,
        satMath25: 770,
        satMath75: 800,
        satVerbal25: 720,
        satVerbal75: 780,
        actComposite25: 34,
        actComposite75: 36,
        avgSatScore: 1530,
        avgActScore: 35,
        internationalEngReqs: {
          toefl: { minimum: 100, recommended: 110 },
          ielts: { minimum: 7.5, recommended: 8.0 }
        },

        tuitionInState: 62484,
        tuitionOutState: 62484,
        tuitionInternational: 62484,
        roomAndBoard: 19922,
        booksAndSupplies: 1200,
        costOfLiving: 2500,
        percentReceivingAid: 0.56,
        averageGrantAid: 57000,
        averageNetPrice: 16000,
        needBlindAdmission: true,
        scholarshipsIntl: true,

        studentPopulation: 17381,
        undergraduatePopulation: 8049,
        graduatePopulation: 9332,
        studentFacultyRatio: 5,
        percentMale: 0.51,
        percentFemale: 0.49,
        percentInternational: 0.24,
        diversityScore: 0.88,

        graduationRate: 0.94,
        retentionRate: 0.98,
        employmentRate: 0.93,
        averageStartingSalary: 98000,
        internshipSupport: 5,
        alumniNetwork: 5,
        visaDurationMonths: 36,

        academicCalendar: AcademicCalendar.QUARTER,
        sportsDivision: "NCAA Division I",
        hasHousing: true,
        studentLifeScore: 4.7,
        partySceneRating: 3.5,
        safetyRating: 4.9,

        popularMajors: ["Computer Science", "Engineering", "Business", "Biology", "Economics"],
        degreeLevels: ["Bachelor's", "Master's", "PhD", "MD", "JD", "MBA"],
        languages: ["English"],
        studentLifeTags: ["Entrepreneurial", "Innovative", "Collaborative", "Athletic"],
        rankings: { usNews: 3, forbes: 1, qs: 3 },
      },
      {
        name: "University of Oxford",
        slug: "oxford",
        shortName: "Oxford",
        description: "The oldest university in the English-speaking world, Oxford is renowned for its tutorial teaching method and centuries of academic tradition.",
        city: "Oxford",
        state: "Oxfordshire",
        zipCode: "OX1 2JD",
        country: "UK",
        address: "Wellington Square",
        latitude: 51.7548,
        longitude: -1.2544,
        logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Oxford-University-Circlet.svg/1200px-Oxford-University-Circlet.svg.png",
        heroImageUrl: "https://images.unsplash.com/photo-1547516509-03497e61c72b?w=1200&h=600&fit=crop",
        websiteUrl: "https://www.ox.ac.uk",
        established: 1096,

        climateZone: "Temperate",
        nearestAirport: "London Heathrow (LHR)",
        region: "South England",
        setting: CampusSetting.URBAN,
        campusSizeAcres: 500,

        type: InstitutionType.PUBLIC,
        classification: "Collegiate University",

        acceptanceRate: 0.17,
        applicationFee: 75,
        commonAppAccepted: false,
        applicationDeadline: new Date("2023-10-15"),
        testPolicy: TestPolicy.REQUIRED,
        minGpa: 3.7,
        avgGpa: 4.0,
        satMath25: 700,
        satMath75: 780,
        satVerbal25: 700,
        satVerbal75: 780,
        actComposite25: 32,
        actComposite75: 35,
        avgSatScore: 1470,
        avgActScore: 33,
        internationalEngReqs: {
          ielts: { minimum: 7.5, recommended: 8.0 },
          toefl: { minimum: 110, recommended: 115 }
        },

        tuitionInState: 12000,
        tuitionOutState: 45000,
        tuitionInternational: 45000,
        roomAndBoard: 15000,
        booksAndSupplies: 800,
        costOfLiving: 12000,
        percentReceivingAid: 0.40,
        averageGrantAid: 20000,
        averageNetPrice: 35000,
        needBlindAdmission: false,
        scholarshipsIntl: true,

        studentPopulation: 24000,
        undergraduatePopulation: 12000,
        graduatePopulation: 12000,
        studentFacultyRatio: 11,
        percentMale: 0.48,
        percentFemale: 0.52,
        percentInternational: 0.45,
        diversityScore: 0.82,

        graduationRate: 0.98,
        retentionRate: 0.97,
        employmentRate: 0.91,
        averageStartingSalary: 75000,
        internshipSupport: 4,
        alumniNetwork: 5,
        visaDurationMonths: 24,

        academicCalendar: AcademicCalendar.TRIMESTER,
        sportsDivision: "None",
        hasHousing: true,
        studentLifeScore: 4.2,
        partySceneRating: 3.5,
        safetyRating: 4.9,

        popularMajors: ["Philosophy", "PPE", "Law", "Medicine", "History"],
        degreeLevels: ["Bachelor's", "Master's", "PhD"],
        languages: ["English"],
        studentLifeTags: ["Traditional", "Academic", "Collegiate", "Historic"],
        rankings: { usNews: 5, forbes: 4, qs: 4 },
      },
      {
        name: "Harvard University",
        slug: "harvard",
        shortName: "Harvard",
        description: "One of the world's most prestigious universities, Harvard is known for academic excellence, influential alumni, and rich history dating back to 1636.",
        city: "Cambridge",
        state: "MA",
        zipCode: "02138",
        country: "USA",
        address: "Massachusetts Hall",
        latitude: 42.3770,
        longitude: -71.1167,
        logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Harvard_shield_wreath.svg/1200px-Harvard_shield_wreath.svg.png",
        heroImageUrl: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=1200&h=600&fit=crop",
        websiteUrl: "https://www.harvard.edu",
        established: 1636,

        climateZone: "Temperate",
        nearestAirport: "Boston Logan (BOS)",
        region: "Northeast",
        setting: CampusSetting.URBAN,
        campusSizeAcres: 209,

        type: InstitutionType.PRIVATE_NON_PROFIT,
        classification: "Research University",

        acceptanceRate: 0.031,
        applicationFee: 85,
        commonAppAccepted: true,
        applicationDeadline: new Date("2024-01-01"),
        earlyDecisionDeadline: new Date("2023-11-01"),
        testPolicy: TestPolicy.OPTIONAL,
        minGpa: 3.9,
        avgGpa: 4.18,
        satMath25: 750,
        satMath75: 800,
        satVerbal25: 730,
        satVerbal75: 780,
        actComposite25: 34,
        actComposite75: 36,
        avgSatScore: 1535,
        avgActScore: 35,
        internationalEngReqs: {
          toefl: { minimum: 100, recommended: 110 },
          ielts: { minimum: 7.5, recommended: 8.0 }
        },

        tuitionInState: 54269,
        tuitionOutState: 54269,
        tuitionInternational: 54269,
        roomAndBoard: 19503,
        booksAndSupplies: 1000,
        costOfLiving: 2500,
        percentReceivingAid: 0.55,
        averageGrantAid: 58000,
        averageNetPrice: 13000,
        needBlindAdmission: true,
        scholarshipsIntl: true,

        studentPopulation: 23100,
        undergraduatePopulation: 7100,
        graduatePopulation: 16200,
        studentFacultyRatio: 6,
        percentMale: 0.49,
        percentFemale: 0.51,
        percentInternational: 0.25,
        diversityScore: 0.87,

        graduationRate: 0.97,
        retentionRate: 0.98,
        employmentRate: 0.95,
        averageStartingSalary: 92000,
        internshipSupport: 5,
        alumniNetwork: 5,
        visaDurationMonths: 36,

        academicCalendar: AcademicCalendar.SEMESTER,
        sportsDivision: "NCAA Division I",
        hasHousing: true,
        studentLifeScore: 4.6,
        partySceneRating: 3.5,
        safetyRating: 4.7,

        popularMajors: ["Economics", "Political Science", "Computer Science", "Psychology", "Social Studies"],
        degreeLevels: ["Bachelor's", "Master's", "PhD", "JD", "MD", "MBA"],
        languages: ["English"],
        studentLifeTags: ["Prestigious", "Academic", "Networking", "Historic"],
        rankings: { usNews: 2, forbes: 3, qs: 2 },
      },
      {
        name: "University of California, Berkeley",
        slug: "uc-berkeley",
        shortName: "UC Berkeley",
        description: "A top public research university known for academic excellence, social activism, and innovation. Located in the San Francisco Bay Area.",
        city: "Berkeley",
        state: "CA",
        zipCode: "94720",
        country: "USA",
        address: "200 California Hall",
        latitude: 37.8719,
        longitude: -122.2585,
        logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Seal_of_University_of_California%2C_Berkeley.svg/1200px-Seal_of_University_of_California%2C_Berkeley.svg.png",
        heroImageUrl: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=1200&h=600&fit=crop",
        websiteUrl: "https://www.berkeley.edu",
        established: 1868,

        climateZone: "Mediterranean",
        nearestAirport: "San Francisco (SFO) / Oakland (OAK)",
        region: "West Coast",
        setting: CampusSetting.URBAN,
        campusSizeAcres: 1232,

        type: InstitutionType.PUBLIC,
        classification: "Research University",

        acceptanceRate: 0.14,
        applicationFee: 70,
        commonAppAccepted: false,
        applicationDeadline: new Date("2023-11-30"),
        testPolicy: TestPolicy.BLIND,
        minGpa: 3.7,
        avgGpa: 3.89,
        satMath25: 650,
        satMath75: 780,
        satVerbal25: 630,
        satVerbal75: 750,
        actComposite25: 28,
        actComposite75: 34,
        avgSatScore: 1415,
        avgActScore: 31,
        internationalEngReqs: {
          toefl: { minimum: 80, recommended: 100 },
          ielts: { minimum: 6.5, recommended: 7.0 }
        },

        tuitionInState: 14253,
        tuitionOutState: 44206,
        tuitionInternational: 44206,
        roomAndBoard: 17000,
        booksAndSupplies: 1200,
        costOfLiving: 3500,
        percentReceivingAid: 0.65,
        averageGrantAid: 22000,
        averageNetPrice: 18000,
        needBlindAdmission: false,
        scholarshipsIntl: true,

        studentPopulation: 45000,
        undergraduatePopulation: 31000,
        graduatePopulation: 14000,
        studentFacultyRatio: 19,
        percentMale: 0.48,
        percentFemale: 0.52,
        percentInternational: 0.17,
        diversityScore: 0.90,

        graduationRate: 0.91,
        retentionRate: 0.97,
        employmentRate: 0.89,
        averageStartingSalary: 75000,
        internshipSupport: 4,
        alumniNetwork: 5,
        visaDurationMonths: 36,

        academicCalendar: AcademicCalendar.SEMESTER,
        sportsDivision: "NCAA Division I",
        hasHousing: true,
        studentLifeScore: 4.4,
        partySceneRating: 4.2,
        safetyRating: 4.1,

        popularMajors: ["Computer Science", "Economics", "Political Science", "Engineering", "Business"],
        degreeLevels: ["Bachelor's", "Master's", "PhD"],
        languages: ["English"],
        studentLifeTags: ["Activist", "Diverse", "Innovative", "Public"],
        rankings: { usNews: 20, forbes: 15, qs: 27 },
      },
      {
        name: "Yale University",
        slug: "yale",
        shortName: "Yale",
        description: "A prestigious Ivy League university known for its residential college system, law school, and strong liberal arts tradition.",
        city: "New Haven",
        state: "CT",
        zipCode: "06520",
        country: "USA",
        address: "2 Whitney Ave",
        latitude: 41.3163,
        longitude: -72.9223,
        logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Yale_University_Shield_1.svg/1200px-Yale_University_Shield_1.svg.png",
        heroImageUrl: "https://images.unsplash.com/photo-1519452635265-7b1fbfd1e4e0?w=1200&h=600&fit=crop",
        websiteUrl: "https://www.yale.edu",
        established: 1701,

        climateZone: "Temperate",
        nearestAirport: "Bradley (BDL) / New York (JFK)",
        region: "Northeast",
        setting: CampusSetting.URBAN,
        campusSizeAcres: 1015,

        type: InstitutionType.PRIVATE_NON_PROFIT,
        classification: "Research University",

        acceptanceRate: 0.047,
        applicationFee: 80,
        commonAppAccepted: true,
        applicationDeadline: new Date("2024-01-02"),
        earlyDecisionDeadline: new Date("2023-11-01"),
        testPolicy: TestPolicy.OPTIONAL,
        minGpa: 3.85,
        avgGpa: 4.14,
        satMath25: 740,
        satMath75: 800,
        satVerbal25: 730,
        satVerbal75: 780,
        actComposite25: 33,
        actComposite75: 36,
        avgSatScore: 1520,
        avgActScore: 34,
        internationalEngReqs: {
          toefl: { minimum: 100, recommended: 110 },
          ielts: { minimum: 7.5, recommended: 8.0 }
        },

        tuitionInState: 62250,
        tuitionOutState: 62250,
        tuitionInternational: 62250,
        roomAndBoard: 18490,
        booksAndSupplies: 1000,
        costOfLiving: 2200,
        percentReceivingAid: 0.52,
        averageGrantAid: 60000,
        averageNetPrice: 14000,
        needBlindAdmission: true,
        scholarshipsIntl: true,

        studentPopulation: 14500,
        undergraduatePopulation: 6500,
        graduatePopulation: 8000,
        studentFacultyRatio: 6,
        percentMale: 0.49,
        percentFemale: 0.51,
        percentInternational: 0.21,
        diversityScore: 0.85,

        graduationRate: 0.96,
        retentionRate: 0.99,
        employmentRate: 0.93,
        averageStartingSalary: 85000,
        internshipSupport: 5,
        alumniNetwork: 5,
        visaDurationMonths: 36,

        academicCalendar: AcademicCalendar.SEMESTER,
        sportsDivision: "NCAA Division I",
        hasHousing: true,
        studentLifeScore: 4.5,
        partySceneRating: 3.8,
        safetyRating: 4.6,

        popularMajors: ["Economics", "Political Science", "History", "Biology", "English"],
        degreeLevels: ["Bachelor's", "Master's", "PhD", "JD", "MD", "MBA"],
        languages: ["English"],
        studentLifeTags: ["Residential", "Ivy League", "Traditional", "Arts-focused"],
        rankings: { usNews: 5, forbes: 6, qs: 16 },
      },
      {
        name: "Princeton University",
        slug: "princeton",
        shortName: "Princeton",
        description: "A world-renowned research university with a focus on undergraduate education and beautiful gothic architecture.",
        city: "Princeton",
        state: "NJ",
        zipCode: "08544",
        country: "USA",
        address: "1 Nassau Hall",
        latitude: 40.3573,
        longitude: -74.6672,
        logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Princeton_seal.svg/1200px-Princeton_seal.svg.png",
        heroImageUrl: "https://images.unsplash.com/photo-1562774053-701939374585?w=1200&h=600&fit=crop",
        websiteUrl: "https://www.princeton.edu",
        established: 1746,

        climateZone: "Temperate",
        nearestAirport: "Newark (EWR) / Philadelphia (PHL)",
        region: "Northeast",
        setting: CampusSetting.SUBURBAN,
        campusSizeAcres: 600,

        type: InstitutionType.PRIVATE_NON_PROFIT,
        classification: "Research University",

        acceptanceRate: 0.042,
        applicationFee: 70,
        commonAppAccepted: true,
        applicationDeadline: new Date("2024-01-01"),
        earlyDecisionDeadline: new Date("2023-11-01"),
        testPolicy: TestPolicy.REQUIRED,
        minGpa: 3.9,
        avgGpa: 4.16,
        satMath25: 760,
        satMath75: 800,
        satVerbal25: 720,
        satVerbal75: 780,
        actComposite25: 34,
        actComposite75: 36,
        avgSatScore: 1530,
        avgActScore: 35,
        internationalEngReqs: {
          toefl: { minimum: 100, recommended: 110 },
          ielts: { minimum: 7.5, recommended: 8.0 }
        },

        tuitionInState: 59710,
        tuitionOutState: 59710,
        tuitionInternational: 59710,
        roomAndBoard: 19300,
        booksAndSupplies: 950,
        costOfLiving: 2000,
        percentReceivingAid: 0.60,
        averageGrantAid: 61000,
        averageNetPrice: 12000,
        needBlindAdmission: true,
        scholarshipsIntl: true,

        studentPopulation: 8800,
        undergraduatePopulation: 5400,
        graduatePopulation: 3400,
        studentFacultyRatio: 5,
        percentMale: 0.51,
        percentFemale: 0.49,
        percentInternational: 0.23,
        diversityScore: 0.83,

        graduationRate: 0.97,
        retentionRate: 0.98,
        employmentRate: 0.94,
        averageStartingSalary: 88000,
        internshipSupport: 5,
        alumniNetwork: 5,
        visaDurationMonths: 36,

        academicCalendar: AcademicCalendar.SEMESTER,
        sportsDivision: "NCAA Division I",
        hasHousing: true,
        studentLifeScore: 4.6,
        partySceneRating: 3.4,
        safetyRating: 4.8,

        popularMajors: ["Economics", "Computer Science", "Public Policy", "Engineering", "Mathematics"],
        degreeLevels: ["Bachelor's", "Master's", "PhD"],
        languages: ["English"],
        studentLifeTags: ["Undergraduate-focused", "Research", "Traditional", "Eating clubs"],
        rankings: { usNews: 1, forbes: 5, qs: 16 },
      },
      {
        name: "California Institute of Technology",
        slug: "caltech",
        shortName: "Caltech",
        description: "A small but mighty science and engineering powerhouse known for its rigorous academics and Nobel Prize-winning faculty.",
        city: "Pasadena",
        state: "CA",
        zipCode: "91125",
        country: "USA",
        address: "1200 E California Blvd",
        latitude: 34.1377,
        longitude: -118.1253,
        logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Caltech_Seal.svg/1200px-Caltech_Seal.svg.png",
        heroImageUrl: "https://images.unsplash.com/photo-1577896851231-70ef18881754?w=1200&h=600&fit=crop",
        websiteUrl: "https://www.caltech.edu",
        established: 1891,

        climateZone: "Mediterranean",
        nearestAirport: "Los Angeles (LAX)",
        region: "West Coast",
        setting: CampusSetting.SUBURBAN,
        campusSizeAcres: 124,

        type: InstitutionType.PRIVATE_NON_PROFIT,
        classification: "Research University",

        acceptanceRate: 0.034,
        applicationFee: 75,
        commonAppAccepted: true,
        applicationDeadline: new Date("2024-01-03"),
        earlyDecisionDeadline: new Date("2023-11-01"),
        testPolicy: TestPolicy.REQUIRED,
        minGpa: 3.9,
        avgGpa: 4.19,
        satMath25: 790,
        satMath75: 800,
        satVerbal25: 740,
        satVerbal75: 780,
        actComposite25: 35,
        actComposite75: 36,
        avgSatScore: 1555,
        avgActScore: 36,
        internationalEngReqs: {
          toefl: { minimum: 100, recommended: 110 },
          ielts: { minimum: 7.5, recommended: 8.0 }
        },

        tuitionInState: 60816,
        tuitionOutState: 60816,
        tuitionInternational: 60816,
        roomAndBoard: 20082,
        booksAndSupplies: 1200,
        costOfLiving: 2500,
        percentReceivingAid: 0.58,
        averageGrantAid: 54000,
        averageNetPrice: 15000,
        needBlindAdmission: true,
        scholarshipsIntl: true,

        studentPopulation: 2400,
        undergraduatePopulation: 980,
        graduatePopulation: 1420,
        studentFacultyRatio: 3,
        percentMale: 0.59,
        percentFemale: 0.41,
        percentInternational: 0.30,
        diversityScore: 0.75,

        graduationRate: 0.93,
        retentionRate: 0.97,
        employmentRate: 0.91,
        averageStartingSalary: 105000,
        internshipSupport: 4,
        alumniNetwork: 4,
        visaDurationMonths: 36,

        academicCalendar: AcademicCalendar.QUARTER,
        sportsDivision: "NCAA Division III",
        hasHousing: true,
        studentLifeScore: 4.0,
        partySceneRating: 2.5,
        safetyRating: 4.7,

        popularMajors: ["Physics", "Computer Science", "Engineering", "Mathematics", "Chemistry"],
        degreeLevels: ["Bachelor's", "Master's", "PhD"],
        languages: ["English"],
        studentLifeTags: ["STEM-focused", "Small", "Intense", "Collaborative"],
        rankings: { usNews: 10, forbes: 9, qs: 15 },
      },
      {
        name: "University of Cambridge",
        slug: "cambridge",
        shortName: "Cambridge",
        description: "One of the world's oldest and most prestigious universities, known for its collegiate system and academic excellence.",
        city: "Cambridge",
        state: "Cambridgeshire",
        zipCode: "CB2 1TN",
        country: "UK",
        address: "The Old Schools, Trinity Ln",
        latitude: 52.2043,
        longitude: 0.1218,
        logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/University_of_Cambridge_coat_of_arms.svg/1200px-University_of_Cambridge_coat_of_arms.svg.png",
        heroImageUrl: "https://images.unsplash.com/photo-1583225646464-51c5dd9a2e8a?w=1200&h=600&fit=crop",
        websiteUrl: "https://www.cam.ac.uk",
        established: 1209,

        climateZone: "Temperate",
        nearestAirport: "London Stansted (STN) / Heathrow (LHR)",
        region: "East England",
        setting: CampusSetting.URBAN,
        campusSizeAcres: 700,

        type: InstitutionType.PUBLIC,
        classification: "Collegiate University",

        acceptanceRate: 0.21,
        applicationFee: 70,
        commonAppAccepted: false,
        applicationDeadline: new Date("2023-10-15"),
        testPolicy: TestPolicy.REQUIRED,
        minGpa: 3.8,
        avgGpa: 4.0,
        satMath25: 720,
        satMath75: 800,
        satVerbal25: 710,
        satVerbal75: 780,
        actComposite25: 33,
        actComposite75: 36,
        avgSatScore: 1485,
        avgActScore: 34,
        internationalEngReqs: {
          ielts: { minimum: 7.5, recommended: 8.0 },
          toefl: { minimum: 110, recommended: 115 }
        },

        tuitionInState: 11000,
        tuitionOutState: 38000,
        tuitionInternational: 38000,
        roomAndBoard: 13000,
        booksAndSupplies: 800,
        costOfLiving: 11000,
        percentReceivingAid: 0.45,
        averageGrantAid: 18000,
        averageNetPrice: 32000,
        needBlindAdmission: false,
        scholarshipsIntl: true,

        studentPopulation: 23000,
        undergraduatePopulation: 12000,
        graduatePopulation: 11000,
        studentFacultyRatio: 10,
        percentMale: 0.50,
        percentFemale: 0.50,
        percentInternational: 0.40,
        diversityScore: 0.80,

        graduationRate: 0.98,
        retentionRate: 0.98,
        employmentRate: 0.92,
        averageStartingSalary: 72000,
        internshipSupport: 4,
        alumniNetwork: 5,
        visaDurationMonths: 24,

        academicCalendar: AcademicCalendar.TRIMESTER,
        sportsDivision: "None",
        hasHousing: true,
        studentLifeScore: 4.3,
        partySceneRating: 3.7,
        safetyRating: 4.8,

        popularMajors: ["Mathematics", "Natural Sciences", "Engineering", "Computer Science", "Economics"],
        degreeLevels: ["Bachelor's", "Master's", "PhD"],
        languages: ["English"],
        studentLifeTags: ["Traditional", "Collegiate", "Research", "Historic"],
        rankings: { usNews: 6, forbes: 7, qs: 2 },
      },
      {
        name: "Columbia University",
        slug: "columbia",
        shortName: "Columbia",
        description: "An Ivy League university in Manhattan, known for its Core Curriculum, journalism school, and vibrant NYC location.",
        city: "New York",
        state: "NY",
        zipCode: "10027",
        country: "USA",
        address: "116th St & Broadway",
        latitude: 40.8075,
        longitude: -73.9626,
        logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Columbia_University_shield.svg/1200px-Columbia_University_shield.svg.png",
        heroImageUrl: "https://images.unsplash.com/photo-1567095761054-7a02e69e5c43?w=1200&h=600&fit=crop",
        websiteUrl: "https://www.columbia.edu",
        established: 1754,

        climateZone: "Temperate",
        nearestAirport: "LaGuardia (LGA) / JFK / Newark (EWR)",
        region: "Northeast",
        setting: CampusSetting.URBAN,
        campusSizeAcres: 36,

        type: InstitutionType.PRIVATE_NON_PROFIT,
        classification: "Research University",

        acceptanceRate: 0.038,
        applicationFee: 85,
        commonAppAccepted: true,
        applicationDeadline: new Date("2024-01-01"),
        earlyDecisionDeadline: new Date("2023-11-01"),
        testPolicy: TestPolicy.OPTIONAL,
        minGpa: 3.85,
        avgGpa: 4.15,
        satMath25: 750,
        satMath75: 800,
        satVerbal25: 730,
        satVerbal75: 780,
        actComposite25: 34,
        actComposite75: 36,
        avgSatScore: 1530,
        avgActScore: 35,
        internationalEngReqs: {
          toefl: { minimum: 100, recommended: 110 },
          ielts: { minimum: 7.5, recommended: 8.0 }
        },

        tuitionInState: 68400,
        tuitionOutState: 68400,
        tuitionInternational: 68400,
        roomAndBoard: 16800,
        booksAndSupplies: 1400,
        costOfLiving: 3500,
        percentReceivingAid: 0.50,
        averageGrantAid: 59000,
        averageNetPrice: 17000,
        needBlindAdmission: true,
        scholarshipsIntl: true,

        studentPopulation: 33000,
        undergraduatePopulation: 8500,
        graduatePopulation: 24500,
        studentFacultyRatio: 6,
        percentMale: 0.47,
        percentFemale: 0.53,
        percentInternational: 0.35,
        diversityScore: 0.88,

        graduationRate: 0.95,
        retentionRate: 0.99,
        employmentRate: 0.93,
        averageStartingSalary: 86000,
        internshipSupport: 5,
        alumniNetwork: 5,
        visaDurationMonths: 36,

        academicCalendar: AcademicCalendar.SEMESTER,
        sportsDivision: "NCAA Division I",
        hasHousing: true,
        studentLifeScore: 4.5,
        partySceneRating: 4.0,
        safetyRating: 4.3,

        popularMajors: ["Economics", "Political Science", "Computer Science", "Engineering", "Neuroscience"],
        degreeLevels: ["Bachelor's", "Master's", "PhD", "JD", "MD", "MBA"],
        languages: ["English"],
        studentLifeTags: ["Urban", "Diverse", "Core Curriculum", "NYC"],
        rankings: { usNews: 12, forbes: 11, qs: 23 },
      },
      {
        name: "University of Chicago",
        slug: "uchicago",
        shortName: "UChicago",
        description: "Known for its rigorous academics, quirky culture, and influential economics department. Where fun comes to die, but excellence thrives.",
        city: "Chicago",
        state: "IL",
        zipCode: "60637",
        country: "USA",
        address: "5801 S Ellis Ave",
        latitude: 41.7886,
        longitude: -87.5987,
        logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/University_of_Chicago_shield.svg/1200px-University_of_Chicago_shield.svg.png",
        heroImageUrl: "https://images.unsplash.com/photo-1569965448-19a44c7f50b3?w=1200&h=600&fit=crop",
        websiteUrl: "https://www.uchicago.edu",
        established: 1890,

        climateZone: "Continental",
        nearestAirport: "Chicago O'Hare (ORD) / Midway (MDW)",
        region: "Midwest",
        setting: CampusSetting.URBAN,
        campusSizeAcres: 217,

        type: InstitutionType.PRIVATE_NON_PROFIT,
        classification: "Research University",

        acceptanceRate: 0.054,
        applicationFee: 75,
        commonAppAccepted: true,
        applicationDeadline: new Date("2024-01-02"),
        earlyDecisionDeadline: new Date("2023-11-01"),
        testPolicy: TestPolicy.OPTIONAL,
        minGpa: 3.8,
        avgGpa: 4.11,
        satMath25: 760,
        satMath75: 800,
        satVerbal25: 740,
        satVerbal75: 780,
        actComposite25: 34,
        actComposite75: 36,
        avgSatScore: 1540,
        avgActScore: 35,
        internationalEngReqs: {
          toefl: { minimum: 100, recommended: 110 },
          ielts: { minimum: 7.5, recommended: 8.0 }
        },

        tuitionInState: 65619,
        tuitionOutState: 65619,
        tuitionInternational: 65619,
        roomAndBoard: 19644,
        booksAndSupplies: 1800,
        costOfLiving: 2500,
        percentReceivingAid: 0.61,
        averageGrantAid: 56000,
        averageNetPrice: 16000,
        needBlindAdmission: true,
        scholarshipsIntl: true,

        studentPopulation: 18500,
        undergraduatePopulation: 7500,
        graduatePopulation: 11000,
        studentFacultyRatio: 5,
        percentMale: 0.50,
        percentFemale: 0.50,
        percentInternational: 0.20,
        diversityScore: 0.82,

        graduationRate: 0.94,
        retentionRate: 0.99,
        employmentRate: 0.91,
        averageStartingSalary: 78000,
        internshipSupport: 4,
        alumniNetwork: 5,
        visaDurationMonths: 36,

        academicCalendar: AcademicCalendar.QUARTER,
        sportsDivision: "NCAA Division III",
        hasHousing: true,
        studentLifeScore: 4.1,
        partySceneRating: 2.8,
        safetyRating: 4.2,

        popularMajors: ["Economics", "Mathematics", "Biology", "Political Science", "Computer Science"],
        degreeLevels: ["Bachelor's", "Master's", "PhD", "JD", "MD", "MBA"],
        languages: ["English"],
        studentLifeTags: ["Intellectual", "Quirky", "Research", "Core Curriculum"],
        rankings: { usNews: 6, forbes: 10, qs: 11 },
      },
      {
        name: "Duke University",
        slug: "duke",
        shortName: "Duke",
        description: "A prestigious research university known for basketball, strong academics, and beautiful gothic architecture in North Carolina.",
        city: "Durham",
        state: "NC",
        zipCode: "27708",
        country: "USA",
        address: "2138 Campus Dr",
        latitude: 36.0014,
        longitude: -78.9382,
        logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Duke_University_logo.svg/1200px-Duke_University_logo.svg.png",
        heroImageUrl: "https://images.unsplash.com/photo-1562774053-701939374585?w=1200&h=600&fit=crop",
        websiteUrl: "https://www.duke.edu",
        established: 1838,

        climateZone: "Humid Subtropical",
        nearestAirport: "Raleigh-Durham (RDU)",
        region: "Southeast",
        setting: CampusSetting.SUBURBAN,
        campusSizeAcres: 8709,

        type: InstitutionType.PRIVATE_NON_PROFIT,
        classification: "Research University",

        acceptanceRate: 0.056,
        applicationFee: 85,
        commonAppAccepted: true,
        applicationDeadline: new Date("2024-01-02"),
        earlyDecisionDeadline: new Date("2023-11-01"),
        testPolicy: TestPolicy.OPTIONAL,
        minGpa: 3.85,
        avgGpa: 4.13,
        satMath25: 750,
        satMath75: 800,
        satVerbal25: 720,
        satVerbal75: 780,
        actComposite25: 34,
        actComposite75: 36,
        avgSatScore: 1525,
        avgActScore: 35,
        internationalEngReqs: {
          toefl: { minimum: 100, recommended: 110 },
          ielts: { minimum: 7.5, recommended: 8.0 }
        },

        tuitionInState: 63054,
        tuitionOutState: 63054,
        tuitionInternational: 63054,
        roomAndBoard: 18918,
        booksAndSupplies: 1200,
        costOfLiving: 2000,
        percentReceivingAid: 0.53,
        averageGrantAid: 58000,
        averageNetPrice: 16000,
        needBlindAdmission: true,
        scholarshipsIntl: true,

        studentPopulation: 17200,
        undergraduatePopulation: 6800,
        graduatePopulation: 10400,
        studentFacultyRatio: 6,
        percentMale: 0.49,
        percentFemale: 0.51,
        percentInternational: 0.18,
        diversityScore: 0.84,

        graduationRate: 0.96,
        retentionRate: 0.98,
        employmentRate: 0.94,
        averageStartingSalary: 82000,
        internshipSupport: 5,
        alumniNetwork: 5,
        visaDurationMonths: 36,

        academicCalendar: AcademicCalendar.SEMESTER,
        sportsDivision: "NCAA Division I",
        hasHousing: true,
        studentLifeScore: 4.7,
        partySceneRating: 4.5,
        safetyRating: 4.6,

        popularMajors: ["Computer Science", "Public Policy", "Economics", "Biology", "Engineering"],
        degreeLevels: ["Bachelor's", "Master's", "PhD", "JD", "MD", "MBA"],
        languages: ["English"],
        studentLifeTags: ["Athletic", "Research", "Social", "Southern"],
        rankings: { usNews: 7, forbes: 8, qs: 57 },
      },
      {
        name: "Cornell University",
        slug: "cornell",
        shortName: "Cornell",
        description: "An Ivy League university in upstate New York, known for its diverse schools, gorges, and strong programs in engineering and agriculture.",
        city: "Ithaca",
        state: "NY",
        zipCode: "14850",
        country: "USA",
        address: "300 Day Hall",
        latitude: 42.4534,
        longitude: -76.4735,
        logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Cornell_University_seal.svg/1200px-Cornell_University_seal.svg.png",
        heroImageUrl: "https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=1200&h=600&fit=crop",
        websiteUrl: "https://www.cornell.edu",
        established: 1865,

        climateZone: "Temperate",
        nearestAirport: "Syracuse (SYR) / Ithaca (ITH)",
        region: "Northeast",
        setting: CampusSetting.RURAL,
        campusSizeAcres: 2300,

        type: InstitutionType.PRIVATE_NON_PROFIT,
        classification: "Research University",

        acceptanceRate: 0.079,
        applicationFee: 80,
        commonAppAccepted: true,
        applicationDeadline: new Date("2024-01-02"),
        earlyDecisionDeadline: new Date("2023-11-01"),
        testPolicy: TestPolicy.OPTIONAL,
        minGpa: 3.75,
        avgGpa: 4.07,
        satMath25: 720,
        satMath75: 800,
        satVerbal25: 700,
        satVerbal75: 770,
        actComposite25: 33,
        actComposite75: 35,
        avgSatScore: 1485,
        avgActScore: 34,
        internationalEngReqs: {
          toefl: { minimum: 100, recommended: 110 },
          ielts: { minimum: 7.5, recommended: 8.0 }
        },

        tuitionInState: 65204,
        tuitionOutState: 65204,
        tuitionInternational: 65204,
        roomAndBoard: 17402,
        booksAndSupplies: 1000,
        costOfLiving: 1800,
        percentReceivingAid: 0.56,
        averageGrantAid: 52000,
        averageNetPrice: 20000,
        needBlindAdmission: true,
        scholarshipsIntl: true,

        studentPopulation: 25000,
        undergraduatePopulation: 15500,
        graduatePopulation: 9500,
        studentFacultyRatio: 9,
        percentMale: 0.47,
        percentFemale: 0.53,
        percentInternational: 0.24,
        diversityScore: 0.86,

        graduationRate: 0.94,
        retentionRate: 0.97,
        employmentRate: 0.91,
        averageStartingSalary: 76000,
        internshipSupport: 5,
        alumniNetwork: 5,
        visaDurationMonths: 36,

        academicCalendar: AcademicCalendar.SEMESTER,
        sportsDivision: "NCAA Division I",
        hasHousing: true,
        studentLifeScore: 4.4,
        partySceneRating: 4.3,
        safetyRating: 4.5,

        popularMajors: ["Engineering", "Agriculture", "Biology", "Hotel Management", "Computer Science"],
        degreeLevels: ["Bachelor's", "Master's", "PhD", "JD", "MD", "MBA"],
        languages: ["English"],
        studentLifeTags: ["Diverse", "Gorges", "Work hard play hard", "Nature"],
        rankings: { usNews: 17, forbes: 14, qs: 20 },
      },
      {
        name: "Imperial College London",
        slug: "imperial",
        shortName: "Imperial",
        description: "A world-leading science, engineering, medicine and business university in central London.",
        city: "London",
        state: "Greater London",
        zipCode: "SW7 2AZ",
        country: "UK",
        address: "South Kensington Campus",
        latitude: 51.4988,
        longitude: -0.1749,
        logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Imperial_College_London_crest.svg/1200px-Imperial_College_London_crest.svg.png",
        heroImageUrl: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=1200&h=600&fit=crop",
        websiteUrl: "https://www.imperial.ac.uk",
        established: 1907,

        climateZone: "Temperate",
        nearestAirport: "London Heathrow (LHR)",
        region: "London",
        setting: CampusSetting.URBAN,
        campusSizeAcres: 130,

        type: InstitutionType.PUBLIC,
        classification: "Research University",

        acceptanceRate: 0.14,
        applicationFee: 70,
        commonAppAccepted: false,
        applicationDeadline: new Date("2024-01-15"),
        testPolicy: TestPolicy.REQUIRED,
        minGpa: 3.8,
        avgGpa: 4.0,
        satMath25: 750,
        satMath75: 800,
        satVerbal25: 700,
        satVerbal75: 760,
        actComposite25: 33,
        actComposite75: 36,
        avgSatScore: 1490,
        avgActScore: 34,
        internationalEngReqs: {
          ielts: { minimum: 7.0, recommended: 7.5 },
          toefl: { minimum: 100, recommended: 110 }
        },

        tuitionInState: 10000,
        tuitionOutState: 38000,
        tuitionInternational: 38000,
        roomAndBoard: 14000,
        booksAndSupplies: 900,
        costOfLiving: 15000,
        percentReceivingAid: 0.35,
        averageGrantAid: 15000,
        averageNetPrice: 37000,
        needBlindAdmission: false,
        scholarshipsIntl: true,

        studentPopulation: 20000,
        undergraduatePopulation: 11500,
        graduatePopulation: 8500,
        studentFacultyRatio: 11,
        percentMale: 0.60,
        percentFemale: 0.40,
        percentInternational: 0.60,
        diversityScore: 0.88,

        graduationRate: 0.95,
        retentionRate: 0.96,
        employmentRate: 0.93,
        averageStartingSalary: 70000,
        internshipSupport: 4,
        alumniNetwork: 5,
        visaDurationMonths: 24,

        academicCalendar: AcademicCalendar.SEMESTER,
        sportsDivision: "None",
        hasHousing: true,
        studentLifeScore: 4.3,
        partySceneRating: 3.8,
        safetyRating: 4.5,

        popularMajors: ["Engineering", "Medicine", "Physics", "Computer Science", "Business"],
        degreeLevels: ["Bachelor's", "Master's", "PhD", "MD", "MBA"],
        languages: ["English"],
        studentLifeTags: ["STEM-focused", "International", "London", "Research"],
        rankings: { usNews: 13, forbes: 12, qs: 6 },
      },
      {
        name: "ETH Zurich",
        slug: "eth-zurich",
        shortName: "ETH",
        description: "Switzerland's premier science and technology university, known for producing Nobel laureates including Albert Einstein.",
        city: "Zurich",
        state: "Zurich",
        zipCode: "8092",
        country: "Switzerland",
        address: "Rämistrasse 101",
        latitude: 47.3769,
        longitude: 8.5417,
        logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/ETH_Z%C3%BCrich_Logo_black.svg/1200px-ETH_Z%C3%BCrich_Logo_black.svg.png",
        heroImageUrl: "https://images.unsplash.com/photo-1509356843151-3e7d96241e11?w=1200&h=600&fit=crop",
        websiteUrl: "https://ethz.ch",
        established: 1855,

        climateZone: "Temperate",
        nearestAirport: "Zurich (ZRH)",
        region: "Central Switzerland",
        setting: CampusSetting.URBAN,
        campusSizeAcres: 400,

        type: InstitutionType.PUBLIC,
        classification: "Research University",

        acceptanceRate: 0.27,
        applicationFee: 150,
        commonAppAccepted: false,
        applicationDeadline: new Date("2023-12-15"),
        testPolicy: TestPolicy.REQUIRED,
        minGpa: 3.7,
        avgGpa: 3.9,
        satMath25: 730,
        satMath75: 800,
        satVerbal25: 680,
        satVerbal75: 750,
        actComposite25: 32,
        actComposite75: 35,
        avgSatScore: 1465,
        avgActScore: 33,
        internationalEngReqs: {
          ielts: { minimum: 7.0, recommended: 7.5 },
          toefl: { minimum: 100, recommended: 110 }
        },

        tuitionInState: 1500,
        tuitionOutState: 1500,
        tuitionInternational: 1500,
        roomAndBoard: 12000,
        booksAndSupplies: 1000,
        costOfLiving: 18000,
        percentReceivingAid: 0.20,
        averageGrantAid: 8000,
        averageNetPrice: 25000,
        needBlindAdmission: false,
        scholarshipsIntl: true,

        studentPopulation: 24000,
        undergraduatePopulation: 11000,
        graduatePopulation: 13000,
        studentFacultyRatio: 14,
        percentMale: 0.69,
        percentFemale: 0.31,
        percentInternational: 0.40,
        diversityScore: 0.70,

        graduationRate: 0.90,
        retentionRate: 0.94,
        employmentRate: 0.96,
        averageStartingSalary: 95000,
        internshipSupport: 4,
        alumniNetwork: 4,
        visaDurationMonths: 18,

        academicCalendar: AcademicCalendar.SEMESTER,
        sportsDivision: "None",
        hasHousing: true,
        studentLifeScore: 4.2,
        partySceneRating: 3.5,
        safetyRating: 5.0,

        popularMajors: ["Engineering", "Computer Science", "Physics", "Mathematics", "Architecture"],
        degreeLevels: ["Bachelor's", "Master's", "PhD"],
        languages: ["German", "English"],
        studentLifeTags: ["Technical", "International", "Research", "Alpine"],
        rankings: { usNews: 25, forbes: 20, qs: 7 },
      },
      {
        name: "University of Toronto",
        slug: "toronto",
        shortName: "UofT",
        description: "Canada's top university and a global leader in research, located in the heart of Toronto with three campuses.",
        city: "Toronto",
        state: "Ontario",
        zipCode: "M5S 1A1",
        country: "Canada",
        address: "27 King's College Circle",
        latitude: 43.6629,
        longitude: -79.3957,
        logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Coat_of_arms_of_the_University_of_Toronto.svg/1200px-Coat_of_arms_of_the_University_of_Toronto.svg.png",
        heroImageUrl: "https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?w=1200&h=600&fit=crop",
        websiteUrl: "https://www.utoronto.ca",
        established: 1827,

        climateZone: "Continental",
        nearestAirport: "Toronto Pearson (YYZ)",
        region: "Ontario",
        setting: CampusSetting.URBAN,
        campusSizeAcres: 175,

        type: InstitutionType.PUBLIC,
        classification: "Research University",

        acceptanceRate: 0.43,
        applicationFee: 125,
        commonAppAccepted: false,
        applicationDeadline: new Date("2024-01-13"),
        testPolicy: TestPolicy.OPTIONAL,
        minGpa: 3.5,
        avgGpa: 3.8,
        satMath25: 650,
        satMath75: 750,
        satVerbal25: 640,
        satVerbal75: 730,
        actComposite25: 29,
        actComposite75: 33,
        avgSatScore: 1390,
        avgActScore: 31,
        internationalEngReqs: {
          ielts: { minimum: 6.5, recommended: 7.0 },
          toefl: { minimum: 89, recommended: 100 }
        },

        tuitionInState: 6100,
        tuitionOutState: 6100,
        tuitionInternational: 55000,
        roomAndBoard: 15000,
        booksAndSupplies: 1000,
        costOfLiving: 15000,
        percentReceivingAid: 0.40,
        averageGrantAid: 12000,
        averageNetPrice: 30000,
        needBlindAdmission: false,
        scholarshipsIntl: true,

        studentPopulation: 95000,
        undergraduatePopulation: 71000,
        graduatePopulation: 24000,
        studentFacultyRatio: 20,
        percentMale: 0.44,
        percentFemale: 0.56,
        percentInternational: 0.27,
        diversityScore: 0.92,

        graduationRate: 0.86,
        retentionRate: 0.93,
        employmentRate: 0.88,
        averageStartingSalary: 60000,
        internshipSupport: 4,
        alumniNetwork: 5,
        visaDurationMonths: 36,

        academicCalendar: AcademicCalendar.SEMESTER,
        sportsDivision: "U Sports",
        hasHousing: true,
        studentLifeScore: 4.3,
        partySceneRating: 3.8,
        safetyRating: 4.4,

        popularMajors: ["Computer Science", "Engineering", "Business", "Life Sciences", "Social Sciences"],
        degreeLevels: ["Bachelor's", "Master's", "PhD", "MD", "JD", "MBA"],
        languages: ["English"],
        studentLifeTags: ["Diverse", "Urban", "Research", "Large"],
        rankings: { usNews: 18, forbes: 16, qs: 21 },
      },
      {
        name: "University of Michigan - Ann Arbor",
        slug: "michigan",
        shortName: "UMich",
        description: "A top public research university known for its academic excellence, athletics, and vibrant college town atmosphere.",
        city: "Ann Arbor",
        state: "MI",
        zipCode: "48109",
        country: "USA",
        address: "500 S State St",
        latitude: 42.2780,
        longitude: -83.7382,
        logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/University_of_Michigan_logo.svg/1200px-University_of_Michigan_logo.svg.png",
        heroImageUrl: "https://images.unsplash.com/photo-1562774053-701939374585?w=1200&h=600&fit=crop",
        websiteUrl: "https://umich.edu",
        established: 1817,

        climateZone: "Continental",
        nearestAirport: "Detroit (DTW)",
        region: "Midwest",
        setting: CampusSetting.SUBURBAN,
        campusSizeAcres: 3177,

        type: InstitutionType.PUBLIC,
        classification: "Research University",

        acceptanceRate: 0.18,
        applicationFee: 75,
        commonAppAccepted: true,
        applicationDeadline: new Date("2024-02-01"),
        earlyDecisionDeadline: new Date("2023-11-01"),
        testPolicy: TestPolicy.OPTIONAL,
        minGpa: 3.7,
        avgGpa: 3.9,
        satMath25: 690,
        satMath75: 790,
        satVerbal25: 680,
        satVerbal75: 760,
        actComposite25: 31,
        actComposite75: 34,
        avgSatScore: 1435,
        avgActScore: 32,
        internationalEngReqs: {
          toefl: { minimum: 88, recommended: 100 },
          ielts: { minimum: 6.5, recommended: 7.0 }
        },

        tuitionInState: 16736,
        tuitionOutState: 55334,
        tuitionInternational: 55334,
        roomAndBoard: 14068,
        booksAndSupplies: 1048,
        costOfLiving: 2500,
        percentReceivingAid: 0.60,
        averageGrantAid: 18000,
        averageNetPrice: 19000,
        needBlindAdmission: false,
        scholarshipsIntl: true,

        studentPopulation: 49600,
        undergraduatePopulation: 32000,
        graduatePopulation: 17600,
        studentFacultyRatio: 15,
        percentMale: 0.48,
        percentFemale: 0.52,
        percentInternational: 0.18,
        diversityScore: 0.86,

        graduationRate: 0.93,
        retentionRate: 0.97,
        employmentRate: 0.91,
        averageStartingSalary: 73000,
        internshipSupport: 5,
        alumniNetwork: 5,
        visaDurationMonths: 36,

        academicCalendar: AcademicCalendar.TRIMESTER,
        sportsDivision: "NCAA Division I",
        hasHousing: true,
        studentLifeScore: 4.8,
        partySceneRating: 4.7,
        safetyRating: 4.4,

        popularMajors: ["Engineering", "Business", "Computer Science", "Psychology", "Economics"],
        degreeLevels: ["Bachelor's", "Master's", "PhD", "JD", "MD", "MBA"],
        languages: ["English"],
        studentLifeTags: ["Go Blue!", "Athletic", "Research", "School spirit"],
        rankings: { usNews: 25, forbes: 22, qs: 33 },
      },
      {
        name: "Northwestern University",
        slug: "northwestern",
        shortName: "Northwestern",
        description: "A prestigious research university on Lake Michigan, known for journalism, theater, and strong professional schools.",
        city: "Evanston",
        state: "IL",
        zipCode: "60208",
        country: "USA",
        address: "633 Clark St",
        latitude: 42.0551,
        longitude: -87.6750,
        logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Northwestern_University_seal.svg/1200px-Northwestern_University_seal.svg.png",
        heroImageUrl: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=1200&h=600&fit=crop",
        websiteUrl: "https://www.northwestern.edu",
        established: 1851,

        climateZone: "Continental",
        nearestAirport: "Chicago O'Hare (ORD)",
        region: "Midwest",
        setting: CampusSetting.SUBURBAN,
        campusSizeAcres: 240,

        type: InstitutionType.PRIVATE_NON_PROFIT,
        classification: "Research University",

        acceptanceRate: 0.07,
        applicationFee: 75,
        commonAppAccepted: true,
        applicationDeadline: new Date("2024-01-03"),
        earlyDecisionDeadline: new Date("2023-11-01"),
        testPolicy: TestPolicy.OPTIONAL,
        minGpa: 3.8,
        avgGpa: 4.1,
        satMath25: 730,
        satMath75: 800,
        satVerbal25: 710,
        satVerbal75: 770,
        actComposite25: 33,
        actComposite75: 35,
        avgSatScore: 1505,
        avgActScore: 34,
        internationalEngReqs: {
          toefl: { minimum: 100, recommended: 110 },
          ielts: { minimum: 7.5, recommended: 8.0 }
        },

        tuitionInState: 64887,
        tuitionOutState: 64887,
        tuitionInternational: 64887,
        roomAndBoard: 19494,
        booksAndSupplies: 1800,
        costOfLiving: 2200,
        percentReceivingAid: 0.49,
        averageGrantAid: 54000,
        averageNetPrice: 20000,
        needBlindAdmission: true,
        scholarshipsIntl: true,

        studentPopulation: 24000,
        undergraduatePopulation: 9000,
        graduatePopulation: 15000,
        studentFacultyRatio: 6,
        percentMale: 0.47,
        percentFemale: 0.53,
        percentInternational: 0.17,
        diversityScore: 0.83,

        graduationRate: 0.95,
        retentionRate: 0.98,
        employmentRate: 0.93,
        averageStartingSalary: 80000,
        internshipSupport: 5,
        alumniNetwork: 5,
        visaDurationMonths: 36,

        academicCalendar: AcademicCalendar.QUARTER,
        sportsDivision: "NCAA Division I",
        hasHousing: true,
        studentLifeScore: 4.5,
        partySceneRating: 4.0,
        safetyRating: 4.5,

        popularMajors: ["Journalism", "Economics", "Engineering", "Theater", "Communication"],
        degreeLevels: ["Bachelor's", "Master's", "PhD", "JD", "MD", "MBA"],
        languages: ["English"],
        studentLifeTags: ["Big Ten", "Professional", "Lakefront", "Quarter system"],
        rankings: { usNews: 9, forbes: 13, qs: 47 },
      },
      {
        name: "Johns Hopkins University",
        slug: "johns-hopkins",
        shortName: "JHU",
        description: "A world leader in research and medicine, known for its medical school, public health programs, and STEM excellence.",
        city: "Baltimore",
        state: "MD",
        zipCode: "21218",
        country: "USA",
        address: "3400 N Charles St",
        latitude: 39.3299,
        longitude: -76.6205,
        logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Johns_Hopkins_University_seal.svg/1200px-Johns_Hopkins_University_seal.svg.png",
        heroImageUrl: "https://images.unsplash.com/photo-1584467735815-f778f274e296?w=1200&h=600&fit=crop",
        websiteUrl: "https://www.jhu.edu",
        established: 1876,

        climateZone: "Humid Subtropical",
        nearestAirport: "Baltimore (BWI)",
        region: "Mid-Atlantic",
        setting: CampusSetting.URBAN,
        campusSizeAcres: 140,

        type: InstitutionType.PRIVATE_NON_PROFIT,
        classification: "Research University",

        acceptanceRate: 0.071,
        applicationFee: 70,
        commonAppAccepted: true,
        applicationDeadline: new Date("2024-01-03"),
        earlyDecisionDeadline: new Date("2023-11-01"),
        testPolicy: TestPolicy.OPTIONAL,
        minGpa: 3.85,
        avgGpa: 4.11,
        satMath25: 750,
        satMath75: 800,
        satVerbal25: 720,
        satVerbal75: 770,
        actComposite25: 34,
        actComposite75: 36,
        avgSatScore: 1520,
        avgActScore: 35,
        internationalEngReqs: {
          toefl: { minimum: 100, recommended: 110 },
          ielts: { minimum: 7.5, recommended: 8.0 }
        },

        tuitionInState: 62840,
        tuitionOutState: 62840,
        tuitionInternational: 62840,
        roomAndBoard: 17984,
        booksAndSupplies: 1200,
        costOfLiving: 2000,
        percentReceivingAid: 0.52,
        averageGrantAid: 56000,
        averageNetPrice: 17000,
        needBlindAdmission: true,
        scholarshipsIntl: true,

        studentPopulation: 28000,
        undergraduatePopulation: 6000,
        graduatePopulation: 22000,
        studentFacultyRatio: 7,
        percentMale: 0.46,
        percentFemale: 0.54,
        percentInternational: 0.26,
        diversityScore: 0.84,

        graduationRate: 0.94,
        retentionRate: 0.97,
        employmentRate: 0.92,
        averageStartingSalary: 84000,
        internshipSupport: 5,
        alumniNetwork: 5,
        visaDurationMonths: 36,

        academicCalendar: AcademicCalendar.SEMESTER,
        sportsDivision: "NCAA Division III",
        hasHousing: true,
        studentLifeScore: 4.2,
        partySceneRating: 3.2,
        safetyRating: 4.1,

        popularMajors: ["Biomedical Engineering", "Public Health", "Neuroscience", "International Studies", "Biology"],
        degreeLevels: ["Bachelor's", "Master's", "PhD", "MD", "MPH"],
        languages: ["English"],
        studentLifeTags: ["Pre-med", "Research", "Medical", "Competitive"],
        rankings: { usNews: 9, forbes: 17, qs: 25 },
      },
      {
        name: "University College London",
        slug: "ucl",
        shortName: "UCL",
        description: "London's leading multidisciplinary university with a global reputation for teaching and research excellence.",
        city: "London",
        state: "Greater London",
        zipCode: "WC1E 6BT",
        country: "UK",
        address: "Gower St",
        latitude: 51.5246,
        longitude: -0.1340,
        logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/University_College_London_logo.svg/1200px-University_College_London_logo.svg.png",
        heroImageUrl: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=1200&h=600&fit=crop",
        websiteUrl: "https://www.ucl.ac.uk",
        established: 1826,

        climateZone: "Temperate",
        nearestAirport: "London Heathrow (LHR)",
        region: "London",
        setting: CampusSetting.URBAN,
        campusSizeAcres: 40,

        type: InstitutionType.PUBLIC,
        classification: "Research University",

        acceptanceRate: 0.48,
        applicationFee: 70,
        commonAppAccepted: false,
        applicationDeadline: new Date("2024-01-25"),
        testPolicy: TestPolicy.REQUIRED,
        minGpa: 3.5,
        avgGpa: 3.8,
        satMath25: 680,
        satMath75: 760,
        satVerbal25: 670,
        satVerbal75: 750,
        actComposite25: 30,
        actComposite75: 34,
        avgSatScore: 1405,
        avgActScore: 32,
        internationalEngReqs: {
          ielts: { minimum: 6.5, recommended: 7.5 },
          toefl: { minimum: 92, recommended: 100 }
        },

        tuitionInState: 10000,
        tuitionOutState: 32000,
        tuitionInternational: 32000,
        roomAndBoard: 14000,
        booksAndSupplies: 900,
        costOfLiving: 15000,
        percentReceivingAid: 0.40,
        averageGrantAid: 12000,
        averageNetPrice: 34000,
        needBlindAdmission: false,
        scholarshipsIntl: true,

        studentPopulation: 48000,
        undergraduatePopulation: 22000,
        graduatePopulation: 26000,
        studentFacultyRatio: 10,
        percentMale: 0.43,
        percentFemale: 0.57,
        percentInternational: 0.55,
        diversityScore: 0.90,

        graduationRate: 0.92,
        retentionRate: 0.95,
        employmentRate: 0.89,
        averageStartingSalary: 65000,
        internshipSupport: 4,
        alumniNetwork: 5,
        visaDurationMonths: 24,

        academicCalendar: AcademicCalendar.SEMESTER,
        sportsDivision: "None",
        hasHousing: true,
        studentLifeScore: 4.4,
        partySceneRating: 4.0,
        safetyRating: 4.3,

        popularMajors: ["Medicine", "Economics", "Law", "Architecture", "Psychology"],
        degreeLevels: ["Bachelor's", "Master's", "PhD", "MD"],
        languages: ["English"],
        studentLifeTags: ["Diverse", "Central London", "Research", "International"],
        rankings: { usNews: 16, forbes: 18, qs: 8 },
      },
    ]

    const createdUniversities = await Promise.all(
      universities.map(uni => prisma.university.create({ data: uni }))
    )

    return createdUniversities
  }
}
